[profile.default]
src = "src"
out = "out"
libs = ["lib"]
allow_paths = ["../guard"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
optimizer = true
optimizer_runs = 1
via_ir = true

